### ISSUE TITLE
Inclusion of numeric argument in receiver instance creation?

### ISSUE THREAD

**Issue by senocular** [tc39/proposal-array-from-async#22]
From readme [Generic factory method](https://github.com/tc39/proposal-array-from-async#generic-factory-method):

> fromAsync can be transferred to or inherited by any other constructor with a single numeric parameter. In that case, the final result will be the data structure created by that constructor (with 0 as its argument)...

While species and `of()` create arrays with a numeric argument, presumably since they'd be able to have knowledge of predetermined length, shouldn't `fromAsync()` be consistent with `from()` since the length of the iterable would/could be unknown?

```js
class Custom extends Array {
    constructor (length) {
        super()
        console.log('Argument length:', length)
    }
}
Custom.from([1,2,3]) // Argument length: undefined
```

**Comment by js-choi** [comment]
Yes, this is a mistake in the explainer. (The specification as written is currently correct, since it is based on Array.from.) I will fix this later.
