### ISSUE TITLE
Using %Array.prototype.values%

### ISSUE THREAD

**Issue by js-choi** [tc39/proposal-array-from-async#29]
Right now, the [proposed algorithm](https://tc39.es/proposal-array-from-async/#sec-array.fromAsync) uses [%Array.prototype.values%](https://tc39.es/ecma262/#sec-array.prototype.values), [CreateArrayIterator](https://tc39.es/ecma262/#sec-createarrayiterator), and [%ArrayIteratorPrototype%](https://tc39.es/ecma262/#sec-%arrayiteratorprototype%-object). This is a shortcut for the machinery that handles non-iterable array-like objects, like Array.prototype.values does. @ljharb pointed out in https://github.com/tc39/proposal-array-from-async/issues/14#issuecomment-1020326595 that we could eventually apply this simplification to [Array.from](https://tc39.es/ecma262/#sec-array.from) as well.

However, @bakkot [pointed out a potential problem on Matrix](https://matrixlogs.bakkot.com/TC39_Delegates/2022-07-17#L2):

> Array.prototype.values produces an iterator which uses the current value of %ArrayIteratorPrototype%.next, which is not what Array.from does[,] so it's not a totally straightforward refactoring

This may also be a problem for Array.fromAsync. We need to closely examine whether we can refactor Array.from *and* Array.fromAsync to use %Array.prototype.values% without any observable difference. The intent has always been to make sure that Array.fromAsync follows Array.from in its treatment of non-iterable array-like objects.

If we are not able to do this soon (before @nicolo-ribaudo and @ljharb perform their Stage-3 reviews again, with the goal being the 2022-09 plenary), then we may have to switch this proposal’s specification not to use %Array.prototype.values% and to defer refactoring to use %Array.prototype.values% later, *after* this proposal is accepted for Stage 4.

**Comment by ljharb** [comment]
Given that problem, which had not occurred to me, it'd indeed probably be simpler for now to remove the values simplification in this proposal.
